// Generates dist/sw.js after `astro build` (wired into the npm build
// script). Walks dist/, content-hashes every precachable file into the
// cache version, and emits a service worker that precaches the whole site
// — it's small, so everything (pages, hashed assets, fonts, icons) is
// available offline after the first visit. Any change to any file yields
// a new cache name; the activate handler drops old caches.
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join, relative, sep } from "node:path";

const dist = fileURLToPath(new URL("../dist/", import.meta.url));

// Reforma1969/1918 ship in public/ but are unused by the site; sw.js is
// this script's own output; .DS_Store is Finder junk copied from public/.
const EXCLUDE = [
	/^fonts\/Reforma1969\//,
	/^fonts\/Reforma1918\//,
	/^sw\.js$/,
	/(^|\/)\.DS_Store$/,
];

function* walk(dir) {
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const path = join(dir, entry.name);
		if (entry.isDirectory()) yield* walk(path);
		else yield path;
	}
}

const files = [...walk(dist)]
	.map((p) => relative(dist, p).split(sep).join("/"))
	.filter((p) => !EXCLUDE.some((re) => re.test(p)))
	.sort();

// Cache HTML under the pretty URLs the site links to (trailingSlash:
// "always"), so navigation requests match cache keys directly.
const urls = files.map((p) =>
	p === "index.html"
		? "/"
		: p.endsWith("/index.html")
			? `/${p.slice(0, -"index.html".length)}`
			: `/${p}`,
);

const hash = createHash("sha256");
for (const f of files) hash.update(f).update(readFileSync(join(dist, f)));
const version = hash.digest("hex").slice(0, 12);

const sw = `// Generated by scripts/generate-sw.mjs — do not edit.
const CACHE = "astrocabula-${version}";
const ASSETS = ${JSON.stringify(urls, null, "\t")};

self.addEventListener("install", (event) => {
	event.waitUntil(
		caches
			.open(CACHE)
			.then((cache) => cache.addAll(ASSETS))
			.then(() => self.skipWaiting()),
	);
});

self.addEventListener("activate", (event) => {
	event.waitUntil(
		caches
			.keys()
			.then((keys) =>
				Promise.all(
					keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)),
				),
			)
			.then(() => self.clients.claim()),
	);
});

// Cache-first: hashed assets and fonts are immutable, and HTML only
// changes on deploy — which ships a byte-different sw.js, so the browser
// reinstalls and swaps the whole cache atomically.
self.addEventListener("fetch", (event) => {
	const { request } = event;
	if (request.method !== "GET") return;
	const url = new URL(request.url);
	if (url.origin !== location.origin) return;
	event.respondWith(
		caches.match(url.pathname).then(
			(hit) =>
				hit ||
				fetch(request).catch(() =>
					request.mode === "navigate" ? caches.match("/") : undefined,
				),
		),
	);
});
`;

writeFileSync(join(dist, "sw.js"), sw);
console.log(
	`sw.js: precaching ${urls.length} URLs (cache astrocabula-${version})`,
);
